apiVersion: v1
kind: Pod
metadata:
    name: myawesomecatapp
spec:
    containers:
      - name: myawesomecatapp
        image: selltom/myawesomecatapp:v0.0.1
        ports:
        - containerPort: 8080
